---
- name: Init | Create list files
  file: path=/etc/apt/sources.list.d/{{ item }} state=touch
  with_items:
    - "mariadb.list"
  tags:
    - init
    - mariadb

- name: Init | Add package repository
  lineinfile: dest="/etc/apt/sources.list.d/{{ item.dest }}" line="{{ item.line }}"
  with_items:
    - { dest: "mariadb.list", line: "deb http://mirror6.layerjet.com/mariadb/repo/10.1/debian jessie main" }
  tags:
    - init
    - mariadb

- name: Init | Update apt cache.
  apt: update_cache=yes
  tags:
    - init
    - mariadb

- name: Build |Â Install MariaDB
  apt: name={{ item }} state=present force=yes
  with_items:
    - mariadb-server
    - python-mysqldb
  tags:
    - build
    - mariadb

- name: Build | Update root password
  mysql_user: name=root password={{ blackroom_mariadb_password }} state=present
  when: blackroom_mariadb_password is defined
  ignore_errors: true
  tags:
    - build
    - mariadb

- name: Build | Check if PHP is installed
  shell: php --version
  ignore_errors: true
  register: php_result
  tags:
    - build
    - mariadb

- name: Build | Install php70-mysql
  apt: name=php7.0-mysql state=present
  when: php_result|success
  tags:
    - build
    - mariadb

- name: Build | Check if python is installed
  shell: python --version
  ignore_errors: true
  register: python_result
  tags:
    - build
    - mariadb

- name: Build | Install python-mysqldb
  apt: name=python-mysqldb state=present
  when: python_result|success
  tags:
    - build
    - mariadb
